/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'fabian' at '5/9/17 11:20 PM' with Gradle 2.14.1
 *
 * @author fabian, @date 5/9/17 11:20 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
